[phases.setup]
nixPkgs = [
  'python311',
  'python311Packages.flask',
  'python311Packages.flask-cors',
  'python311Packages.gunicorn',
  'python311Packages.bcrypt',
  'python311Packages.pydantic',
  'python311Packages.requests',
  'python311Packages.python-dotenv'
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 src.main:app"
