providers = ["python"]

[phases.install]
cmds = [
  'python --version',
  'python -m ensurepip --upgrade',
  'python -m pip install --break-system-packages -r requirements.txt'
]

[start]
cmd = "python -m gunicorn --bind 0.0.0.0:$PORT --timeout 120 src.main:app"


